name: CI Dev Deployment
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Linting
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Build Application
        run: npm run build

      - name: Create Build Archive
        run: |
          cd build
          zip -r ../build.zip .
          cd ..

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build.zip

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Verify Build Artifact
        run: |
          ls -la
          file build.zip

      - name: Create Dev Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ vars.BUILD_TAG || 'dev-v1.0' }}
          NOTE: ${{ vars.RELEASE_NOTE || 'Development build for testing' }}
        run: |
          # Delete tag if it exists
          git tag -d "$TAG" 2>/dev/null || true
          git push origin ":refs/tags/$TAG" 2>/dev/null || true
          
          # Create new release
          gh release create "$TAG" build.zip \
            --title "Development Release $TAG" \
            --notes "$NOTE" \
            --prerelease